{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "oauth2-proxy-config",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "oauth2-proxy-config",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "values.yaml": "AgAkH7stH8AULvqwvewjEMBPf5NJeXuNSXMP+jR303eNyWSUAnaiGT8Ajy6Ht0Q6BdpTqa9/EggarPJ2/xTa8pw3Cf/F4CxRvWqDw+z18gYg+FHMBF2hO24pCRv6FmWpkfaVZozDCaHys+IrpbwJeL6+Ne6OkRAKNDYABqDLQtVIyaBcoICF0TnPsyy0aDo2ziT5nb/pNkTTLArQa2Po10c+kCq5WuzoD/cJ5weIzgjRIcx90TKjq+RwTUqGLfxXvPLElOq2AZg5jNorpPg5KUmYl4WIbN5Nwzmh9tZah4YuYO/wvO0CEDzp7UYGv7ia6A9yts1ogc6yeVFK+o1pJN9UgL0QF9h+fUzCKsntxdDs1lRChcHRuBqWXT3/j0NfOHYASm01O/WXVim2Pfs9kw8OZIFxPwfvSIBC6WfSVwsLYxZXbHYDNg1xkABEICOKu4KqPhVmYkLM/l4gphc/rw+CacBcCmjQoA1QEYDFwa6KRSYkoC+igbgjWUihgYYtcJMHf/CzZrQ9QsJzQ1HZeV9W5BTVpUIr/cI9xSwz5HR6KoxR3O1Im1UNQ78LxqzkMf/xpvS9ogjjC6m8ZLJFNx882/IhZkLmM2shRrAM8s0KksxK6rYiAYKITYVZ0dcEa88aLK77vwMF9WbFPJsEMIctd/ClLHKtxhQinV9nxnRszfgZHLMbUm7hfWTAIdaL9W06n0+Mp85SKFVEpOfpfuCHjOXjtsbI+fdMivItCdMak/44nN4041mF+3q/KOWwosgN1gZLQ2JvSivVGRj8QZanR+78zhq22sbGYqHonXZrsCCdk2sP3GLds6v8n57MCK0tP+Ki5JCkFzwwbX4FI9qI2Y34qQRLRV0ZM8txhmWldDkALSTaeHKPwguKb91seyafUk0435z+LsM93gjXdGpL9OfYrb4oDsKzmlvJtbQRQCYYPmvovznc7+/OI9KyxOpGLZ4k6sPt0x+jNFmxUko9CImLD1TJiFhG8aVRfGjFzkw+HBpImclNnYK8oICtkaw53/RS1sbIXH++T2VcTn03tj9vTOwsQrEexbnGHFgWSAIrXB3Amtu3XoAqbmPvZMu0Djil1xhP74mnaVdQWvzBpFBCiMYVQzvHpaxhdl6AMtthNwgVFDgWnHiKUTN+jjwUF3vJmPFroYu2dN/vARGBTNbaSAJabP7WPpVidrwM3XyPBiWHjVa2sYnTYjsz/yP0cWuwpTd/E4vn/WyMd4Fm/V+YgNs3uNiYR76tXgEiDsdxsGieVW3xhFFZ9S8veh0K5FWjc3aBdNCUaV170wh99IjkaVpsB3FtTUMuVhhkwrqIru88Ey7QMvOxPxd6T9QHh+ga9DjoJRTjncXt63aFfDBkJzAbazvEDXiN2x2swVN8qt9kVliK1nDTGhtOK8+jH41C4JfmxtP+YaGyAQytCQ5SsxIJ84DqWHlxE/MKeoNrWqg/UlO0f/oIwxq9kMGGhtcNvj0cPf5vfYft0fJX0HZaG4oCebbkv7aC4xYRJlVS8sJBIzEKgF7ACBpRw0r4UtXSR3r3iJHiZFhKJU1dt0UId5PF74piJwPeOWQhzvJiGP+/b2qZp/HQWGoq/fDKQHIP7bVk6jQTmzWorBjy9aDqh3H7MTJ9ScMXQvdYsqmfgZrDVRetaU6ET7r7emnkbkDquqtjNfQdQf6w45bFDPu9VPBtRRYiDeeN"
    }
  },
  "status": {

  }
}
