apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth2-proxy-config
  namespace: default
spec:
  encryptedData:
    values.yaml: AgC5sbZ0fMgW8P/Wa1teOQnzbvHa2YcsN5grGlYkGEqkeU3LXALsT9+31tALZr/JtO8BeQ7lKO26nUv1h4LbMeqIeRRlTiKwWronlTGV4RGMY+U8c9gmJkgzlSqtXzDETklXTKl1hm2t3Zik1agPfSXV8K0aYgXCPM7oNoomqU1sAfSK8dgdR5MI5vbV6AIK8xD1p9gjxf5u8hI3hhUtFIAhD8MQcPATqnpDs4lvXPraS2yy9q74X57aU5d/UxdF0p782l5NvYZsw/RoevAxIbACaw9WjuTTolkWeohQMAjd8WgMLj1jc9VPRSqVE5Cg/HlEicUMOka5SCbXHMFpyzKQoRHa6BJ7WGhh1/IGldLCEzEc5NXg5U3Zlni/P3REDkJy9/XjyByhgDLizRbNSnOEhpXUPuwqLxvfCnYewbtTeDRYfGYM5ujQpmhvholv4K302j8qHm7rWD6zo1Th//aEt0FXFUne6N8MH067LJottezQbnt/FaEbNxbnosDXgwdEwVxPX0TjPRlUp7wTYCFMukxYnIoOwKU0PPgrZ/OhR1CUyWK/FY5Pza6viDWBnSuAWrcMuTPh6KYnBphvIv0wvqBQMu7rp9A6+KRl4qwV9ko3gEDd3cSv1vFbSXnxoriZMKu/fOgj/AVCpukpgwn4s7pdZQelUaQqAOcMlNYzihL4CFdE/d4lfj/2cx93IiMTTFX7zjyXN7K2a7lE2JrhP8C0ttElIdw24pMqyCt4TDDorBg8XYhoLNkLZiOvkYMXFPxPMYKELuQRRH8jE7tg0xwIhmuA5gbhpN9Er44UPWyHalbVwZXgqOBmjFcMT0kq793tgvCmR/03qIUdjmCJMpCzBDbSZTYZ10EEtuvkQ1pN8YsMTEyQTSd29x22bpQH6dSpp92t7KHzSrY0FT/kKnQLY6149ZlQNq4V0+BrqdUBK6q9BbB5Rlwhyh/k/vlbWgC+VF6l+CwWyu/rBDB26WyivHkkXtWxynno5y/xq77svAN2uoA5PG3uaTlbDIGPA7tunRVzzd9vkUINfKk9mdnhIKvKSGhA0/vFSEd4fsoPE/03jsd3RDLDWsxZsOasDKtHqJg8UqdPZfKVjNmQlmFgsFAyxwPqi/mzrNxbrMZfw71Z2Fuar+09wW/ZFiNwbGC2vHjpjU6zttXeJg0seyRGkYKsuqBtI4lRHJ6zKWWJEhHvCl5AX+WUxglZ8G3tyw+Y4wE4i5hIuxPaVsBD/N71C0vyj5b6DUpwNge9fS8xDM/dHrvL9/LJamulpgFZCs/h2+oe6BVmLliLUf1inO/Pybn3mTG6oYjDAr+uUn1JzGsAegD24NU1xMj9UVOro0sQAXSXMTRBr13e3crIOtmOiWYpiOkojHzWFR56SkYJY9uWVkChqz1zDq0vFLE0oMNVgn8DKJjSLexOQvzM+t1ys9CddfyzyUjGii/j0gCfm2W3Q7GZlrkaUfh3UcF6dEQ9fqXyxymB7p4Yth/XM260EylYYs6LHclfkDjN+d5m9zZwrzG8XrObzVq5KwC7U0m0xIaTQayAQW0F/COveHr+iEygS6p+f/cTVZLeRWy+fNJSe28rsMEYKPDj8uH4NYYhinE93fj7raf+uYCkPrEVGR1G7DQxTxi97uZCILUGwV4lZOpXTmAG3JxGZUXCQBRFIiaKLxvYV736vBzhBzIU+8AO1M9rS+nTaszh0w==
  template:
    metadata:
      creationTimestamp: null
      name: oauth2-proxy-config
      namespace: default
status: {}

