apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:^4.0.0
spec:
  releaseName: oauth2-proxy
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: oauth2-proxy
    version: 2.1.1
  values:
    image:
      repository: quay.io/pusher/oauth2_proxy
      tag: v4.0.0
    config:
      existingSecret: oauth2-proxy-credentials
    extraArgs:
      whitelist-domain: .internal.juusoleinonen.fi
      cookie-domain: .internal.juusoleinonen.fi
      provider: github
    authenticatedEmailsFile:
      enabled: true
      restricted_access: |-
        leinonen.juuso@gmail.com
    ingress:
      enabled: true
      path: /
      hosts:
        - auth.internal.juusoleinonen.fi
      annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.io/cluster-issuer: letsencrypt-prod
      tls:
        - secretName: oauth2-proxy-https-cert
          hosts:
            - auth.internal.juusoleinonen.fi
