apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:^4.0.0
spec:
  releaseName: oauth2-proxy
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: oauth2-proxy
    version: 2.1.1
  values:
    image:
      repository: quay.io/pusher/oauth2_proxy
      tag: v4.0.0
    valuesFrom:
      - secretKeyRef:
          name: oauth2-proxy-config
