---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:~v0.11.*
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.11.0
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v0.11.1
    webhook:
      enabled: false
