---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.12.0
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v0.12.0
    webhook:
      enabled: false
