apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: influxdb
  labels:
    app.kubernetes.io/component: influxdb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: influxdb
  endpoints:
    - port: http
      path: "/metrics"
  namespaceSelector:
    matchNames:
      - default