---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: infrastructure
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: leinonen.juuso@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-secret
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: infrastructure
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: leinonen.juuso@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-secret
    solvers:
    - http01:
        ingress:
          class: nginx
